# Generated by Django 3.2.13 on 2022-10-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment',
            field=models.CharField(default='없음', max_length=200),
            preserve_default=False,
        ),
    ]
